version: 2.1

executors:
  cpp-python-executor:
    machine:
      image: ubuntu-2204:current
    working_directory: ~/pybindings

jobs:
  build-and-test:
    executor: cpp-python-executor
    steps:
      - checkout

      - restore_cache:
          keys:
            - vcpkg-modules-v1-{{ checksum "vcpkg.json" }}
            - vcpkg-modules-v1-

      - run:
          name: Install System Dependencies
          command: |
            sudo apt-get update
            DEBIAN_FRONTEND=noninteractive sudo apt-get install -y \
              cmake clang clang-tidy ninja-build pkg-config llvm \
              python3.12 python3.12-dev python3.12-venv

      - run:
          name: Install uv
          command: |
            curl -LsSf https://astral.sh/uv/install.sh | sh
            echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> $BASH_ENV

      - run:
          name: Setup vcpkg
          command: |
            git submodule update --init --recursive

      - run:
          name: Bootstrap vcpkg
          command: ./vcpkg/bootstrap-vcpkg.sh

      - run:
          name: Install vcpkg Dependencies
          command: ./vcpkg/vcpkg install --triplet=x64-linux

      - run:
          name: Configure C++ Project
          command: |
            cmake -B build -S . \
              -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake \
              -DCMAKE_CXX_COMPILER=clang++ \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
              -G Ninja

      - run:
          name: Build C++ Project
          command: |
            mkdir -p build/test_results
            cmake --build build

      - run:
          name: Run C++ Tests
          command: |
            cd build
            ctest --output-on-failure --test-output-size-passed | tee test_results/ctest_output.log

      - run:
          name: Install Python Package
          command: |
            source $HOME/.cargo/env
            cd ab_py_calculator
            uv pip install -e ".[dev]"

      - run:
          name: Run Python Tests
          command: |
            source $HOME/.cargo/env
            cd ab_py_calculator
            uv run pytest tests/ -v --junitxml=../build/test_results/pytest.xml

      - run:
          name: Python Code Quality
          command: |
            source $HOME/.cargo/env
            cd ab_py_calculator
            uv run ruff check .
            uv run mypy .

      - store_test_results:
          path: build/test_results

      - store_artifacts:
          path: build/test_results
          destination: test-results

      - save_cache:
          key: vcpkg-modules-v1-{{ checksum "vcpkg.json" }}
          paths:
            - ~/.cache/vcpkg/archives
            - ./vcpkg/installed

workflows:
  version: 2
  build-test-analyze:
    jobs:
      - build-and-test
