# .github/workflows/clang-tidy.yml
name: Clang-Tidy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  clang-tidy:
    name: C++ Static Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-tidy build-essential ninja-build cmake python3-dev \
          autoconf automake libtool pkg-config

    - name: Bootstrap vcpkg
      run: ./vcpkg/bootstrap-vcpkg.sh

    - name: Install vcpkg dependencies
      run: |
        export VCPKG_BINARY_SOURCES="clear;nuget,GitHub,readwrite"
        ./vcpkg/vcpkg install --triplet=x64-linux

    - name: Configure project
      run: |
        cmake -B build -G Ninja \
          -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
          -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake \
          -DCMAKE_CXX_COMPILER=clang++

    - name: Run Clang-Tidy
      run: |
        find src -name '*.cpp' -o -name '*.hpp' | \
        xargs clang-tidy -p build \
        --header-filter='src/.*' \
        --warnings-as-errors='-*,performance-*,bugprone-*' \
        || echo "Clang-tidy found issues but continuing..."
